CREATE TABLE IF NOT EXISTS "users" (
    user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(10),
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    CONSTRAINT phone_number_length CHECK (length(phone_number) <= 10)
);
